### ISSUE TITLE
Asset bundle naming

### ISSUE THREAD

**Issue by xiaoxiao921** [ArcPh1r3/HenryTutorial#4]
https://github.com/ArcPh1r3/HenryTutorial/blob/afa9518e1ff8e801437fcb4c10ed395915590cbc/HenryMod/Modules/Assets.cs#L35-L54

Can be confusing as both line 35 / 54 contains a dot + doesnt compile currently

**Comment by TheTimeSweeper** [comment]
fixed, thanks thanks
